[workspace]
resolver = "3"
members = ["crates/sleepytale"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
aes-gcm = "0.10"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
libc = "0.2"
serde = { version = "1", features = ["derive"] }
socket2 = "0.5"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "process", "io-std", "io-util", "time", "signal", "sync"] }
toml = "0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
